// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: seiprotocol/seichain/evm/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// string base_denom = 1 [
	//   (gogoproto.moretags)   = "yaml:\"base_denom\"",
	//   (gogoproto.jsontag) = "base_denom"
	// ];
	PriorityNormalizer cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=priority_normalizer,json=priorityNormalizer,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"priority_normalizer" yaml:"priority_normalizer"`
	BaseFeePerGas      cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"base_fee_per_gas" yaml:"base_fee_per_gas"`
	MinimumFeePerGas   cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=minimum_fee_per_gas,json=minimumFeePerGas,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"minimum_fee_per_gas" yaml:"minimum_fee_per_gas"`
	// ChainConfig chain_config = 5 [(gogoproto.moretags) = "yaml:\"chain_config\"", (gogoproto.nullable) = false];
	//   string chain_id = 6 [
	//   (gogoproto.moretags)   = "yaml:\"chain_id\"",
	//   (gogoproto.customtype) = "cosmossdk.io/math.Int",
	//   (gogoproto.nullable)   = false,
	//   (gogoproto.jsontag) = "chain_id"
	// ];
	// repeated string whitelisted_codehashes_bank_send = 7 [
	//   (gogoproto.moretags)   = "yaml:\"whitelisted_codehashes_bank_send\"",
	//   (gogoproto.jsontag) = "whitelisted_codehashes_bank_send"
	// ];
	WhitelistedCwCodeHashesForDelegateCall [][]byte `protobuf:"bytes,8,rep,name=whitelisted_cw_code_hashes_for_delegate_call,json=whitelistedCwCodeHashesForDelegateCall,proto3" json:"whitelisted_cw_code_hashes_for_delegate_call" yaml:"whitelisted_cw_code_hashes_for_delegate_call"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b8db1cb709659e2, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWhitelistedCwCodeHashesForDelegateCall() [][]byte {
	if m != nil {
		return m.WhitelistedCwCodeHashesForDelegateCall
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "seiprotocol.seichain.evm.Params")
}

func init() {
	proto.RegisterFile("seiprotocol/seichain/evm/params.proto", fileDescriptor_6b8db1cb709659e2)
}

var fileDescriptor_6b8db1cb709659e2 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0x77, 0x6d, 0x28, 0xba, 0x28, 0x94, 0xad, 0x60, 0x88, 0xb0, 0x53, 0x16, 0x94, 0x1e,
	0xcc, 0xee, 0xa1, 0xb7, 0x1e, 0x93, 0xd2, 0x7a, 0x10, 0x29, 0x7b, 0x12, 0x2f, 0xc3, 0x64, 0xf6,
	0x65, 0x76, 0x70, 0x26, 0x6f, 0x99, 0x99, 0x36, 0x46, 0xff, 0x00, 0xf1, 0xe6, 0xd1, 0xa3, 0xff,
	0x8c, 0xd0, 0x63, 0x8f, 0xe2, 0x61, 0x91, 0xe4, 0x64, 0x8f, 0xf9, 0x0b, 0x24, 0xbb, 0xad, 0x89,
	0x1a, 0xa1, 0xb9, 0x0d, 0xdf, 0xf7, 0x7b, 0x6f, 0x3e, 0x1e, 0x5f, 0xf0, 0xc4, 0x82, 0x2c, 0x0d,
	0x3a, 0xe4, 0xa8, 0x52, 0x0b, 0x92, 0x17, 0x4c, 0x8e, 0x52, 0x38, 0xd7, 0x69, 0xc9, 0x0c, 0xd3,
	0x36, 0xa9, 0xcd, 0xb0, 0xbd, 0x82, 0x25, 0x37, 0x58, 0x02, 0xe7, 0xba, 0xf3, 0x50, 0xa0, 0xc0,
	0xda, 0x4a, 0x17, 0xaf, 0x86, 0xef, 0xfc, 0x7f, 0x2d, 0xc7, 0xd1, 0x50, 0x8a, 0x06, 0x8b, 0x7f,
	0xb6, 0x82, 0xed, 0xd3, 0xfa, 0x9f, 0xf0, 0xa3, 0x1f, 0xec, 0x96, 0x46, 0xa2, 0x91, 0x6e, 0x42,
	0x47, 0x68, 0x34, 0x53, 0xf2, 0x1d, 0x98, 0xf6, 0x9d, 0x3d, 0x7f, 0xff, 0x5e, 0xef, 0xd5, 0x45,
	0x45, 0xbc, 0xef, 0x15, 0x79, 0xcc, 0xd1, 0x6a, 0xb4, 0x36, 0x7f, 0x93, 0x48, 0x4c, 0x35, 0x73,
	0x45, 0xf2, 0x02, 0x04, 0xe3, 0x93, 0x23, 0xe0, 0x57, 0x15, 0x59, 0xb7, 0x61, 0x5e, 0x91, 0xce,
	0x84, 0x69, 0x75, 0x18, 0xaf, 0x31, 0xe3, 0x2c, 0xbc, 0x51, 0x5f, 0xfe, 0x16, 0xc3, 0xf7, 0xc1,
	0xce, 0x80, 0x59, 0xa0, 0x43, 0x00, 0x5a, 0x82, 0xa1, 0x82, 0xd9, 0xf6, 0x56, 0x9d, 0x23, 0xbb,
	0x5d, 0x8e, 0x7f, 0xc6, 0xe7, 0x15, 0x79, 0xd4, 0x84, 0xf8, 0xdb, 0x89, 0xb3, 0x07, 0x0b, 0xe9,
	0x18, 0xe0, 0x14, 0xcc, 0x09, 0xb3, 0xe1, 0x07, 0x3f, 0xd8, 0xd5, 0x72, 0x24, 0xf5, 0x99, 0xfe,
	0x23, 0x40, 0x6b, 0xa3, 0x43, 0xac, 0xd9, 0xb0, 0x3c, 0xc4, 0x1a, 0x33, 0xce, 0x76, 0xae, 0xd5,
	0x65, 0x92, 0xaf, 0x7e, 0xf0, 0x6c, 0x5c, 0x48, 0x07, 0x4a, 0x5a, 0x07, 0x39, 0xe5, 0x63, 0xca,
	0x31, 0x07, 0x5a, 0x30, 0x5b, 0x80, 0xa5, 0x43, 0x34, 0x34, 0x07, 0x05, 0x82, 0x39, 0xa0, 0x9c,
	0x29, 0xd5, 0xbe, 0xbb, 0xb7, 0xb5, 0x7f, 0xbf, 0x27, 0xae, 0x2a, 0xb2, 0xd1, 0xdc, 0xbc, 0x22,
	0x07, 0x4d, 0xb0, 0x4d, 0xa6, 0xe2, 0xec, 0xe9, 0x0a, 0xde, 0x1f, 0xf7, 0x31, 0x87, 0xe7, 0x35,
	0x7b, 0x8c, 0xe6, 0xe8, 0x9a, 0xec, 0x33, 0xa5, 0x0e, 0x5b, 0x9f, 0xbf, 0x10, 0xaf, 0x77, 0x72,
	0x31, 0x8d, 0xfc, 0xcb, 0x69, 0xe4, 0xff, 0x98, 0x46, 0xfe, 0xa7, 0x59, 0xe4, 0x5d, 0xce, 0x22,
	0xef, 0xdb, 0x2c, 0xf2, 0x5e, 0x77, 0x85, 0x74, 0xc5, 0xd9, 0x20, 0xe1, 0xa8, 0x17, 0x5d, 0xed,
	0xae, 0x16, 0xb7, 0xdb, 0x34, 0xf7, 0x6d, 0xdd, 0x5d, 0x37, 0x29, 0xc1, 0x0e, 0xb6, 0x6b, 0xff,
	0xe0, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x71, 0xe6, 0xc8, 0x3b, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for iNdEx := len(m.WhitelistedCwCodeHashesForDelegateCall) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			copy(dAtA[i:], m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.WhitelistedCwCodeHashesForDelegateCall[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	{
		size := m.MinimumFeePerGas.Size()
		i -= size
		if _, err := m.MinimumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BaseFeePerGas.Size()
		i -= size
		if _, err := m.BaseFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PriorityNormalizer.Size()
		i -= size
		if _, err := m.PriorityNormalizer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PriorityNormalizer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinimumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.WhitelistedCwCodeHashesForDelegateCall) > 0 {
		for _, b := range m.WhitelistedCwCodeHashesForDelegateCall {
			l = len(b)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityNormalizer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriorityNormalizer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedCwCodeHashesForDelegateCall", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedCwCodeHashesForDelegateCall = append(m.WhitelistedCwCodeHashesForDelegateCall, make([]byte, postIndex-iNdEx))
			copy(m.WhitelistedCwCodeHashesForDelegateCall[len(m.WhitelistedCwCodeHashesForDelegateCall)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
